// <auto-generated />
using System;
using BrazosApp.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrazosApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240410102640_ModifyApplicationForTableDataToDb")]
    partial class ModifyApplicationForTableDataToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BrazosApp.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationForId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("1='Not Verified', 2='Verified', 3='Expired'");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationForId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("BrazosApp.Models.ApplicationFor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("LanguageTypeId");

                    b.ToTable("ApplicationFor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationTypeId = 1,
                            Code = "RF",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Retail Food New"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationTypeId = 1,
                            Code = "RF",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Retail Food New (Spanish)"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationTypeId = 1,
                            Code = "MF",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Mobile Food New"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationTypeId = 1,
                            Code = "MF",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Mobile Food New (Spanish)"
                        },
                        new
                        {
                            Id = 5,
                            ApplicationTypeId = 1,
                            Code = "RF",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Retail Food Change of Owner"
                        },
                        new
                        {
                            Id = 6,
                            ApplicationTypeId = 1,
                            Code = "RF",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Retail Food Change of Owner (Spanish)"
                        },
                        new
                        {
                            Id = 7,
                            ApplicationTypeId = 1,
                            Code = "MF",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Mobile Food Change of Owner"
                        },
                        new
                        {
                            Id = 8,
                            ApplicationTypeId = 1,
                            Code = "MF",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Mobile Food Change of Owner (Spanish)"
                        },
                        new
                        {
                            Id = 9,
                            ApplicationTypeId = 1,
                            Code = "TF",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Temporary Food"
                        },
                        new
                        {
                            Id = 10,
                            ApplicationTypeId = 1,
                            Code = "TF",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Temporary Food (Spanish)"
                        },
                        new
                        {
                            Id = 11,
                            ApplicationTypeId = 1,
                            Code = "FHEA",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Food Handler Enrollment Application"
                        },
                        new
                        {
                            Id = 12,
                            ApplicationTypeId = 1,
                            Code = "FHEA",
                            IsActive = true,
                            LanguageTypeId = 2,
                            Name = "Food Handler Enrollment Application (Spanish)"
                        },
                        new
                        {
                            Id = 13,
                            ApplicationTypeId = 2,
                            Code = "FH",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Foster Home"
                        },
                        new
                        {
                            Id = 14,
                            ApplicationTypeId = 3,
                            Code = "DS",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Daycare Sanitation"
                        },
                        new
                        {
                            Id = 15,
                            ApplicationTypeId = 4,
                            Code = "PL",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Pools"
                        },
                        new
                        {
                            Id = 16,
                            ApplicationTypeId = 5,
                            Code = "C",
                            IsActive = true,
                            LanguageTypeId = 1,
                            Name = "Complaints"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.ApplicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Foster Home"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Daycare Sanitation"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Pools"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Complaints"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.LanguageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("LanguageType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "E",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SP",
                            IsActive = true,
                            Name = "Spanish"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.PermitStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PermitStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Incomplete"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Pending Admin Review"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Admin Review"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Pending Plan Review"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Plan Review"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Pending Payment"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Pre-Op"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Renewal"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Expired"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Area 51"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RiskCategory");
                });

            modelBuilder.Entity("BrazosApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Admin Inspector"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Inspector"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Clerk"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "View Only"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("BrazosApp.Models.TerritoryAssignedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TerritoryAssignedTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "System Assigned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Default Assigned"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Normal Assigned"
                        });
                });

            modelBuilder.Entity("BrazosApp.Models.TerritoryWiseInspectors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId")
                        .IsUnique();

                    b.HasIndex("TerritoryId");

                    b.HasIndex("TypeId");

                    b.ToTable("TerritoryWiseInspectors");
                });

            modelBuilder.Entity("BrazosApp.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BHCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertifiedPoolOperator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignatedRepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RegisteredSanitarian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SanitarianInTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrazosApp.Models.Application", b =>
                {
                    b.HasOne("BrazosApp.Models.ApplicationFor", "ApplicationFor")
                        .WithMany()
                        .HasForeignKey("ApplicationForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationFor");
                });

            modelBuilder.Entity("BrazosApp.Models.ApplicationFor", b =>
                {
                    b.HasOne("BrazosApp.Models.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrazosApp.Models.LanguageType", "LanguageType")
                        .WithMany()
                        .HasForeignKey("LanguageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationType");

                    b.Navigation("LanguageType");
                });

            modelBuilder.Entity("BrazosApp.Models.TerritoryWiseInspectors", b =>
                {
                    b.HasOne("BrazosApp.Models.Users", "AssignedUser")
                        .WithOne("TerritoryWiseInspectors")
                        .HasForeignKey("BrazosApp.Models.TerritoryWiseInspectors", "AssignedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrazosApp.Models.Territory", "Territory")
                        .WithMany("Inspectors")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrazosApp.Models.TerritoryAssignedType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Territory");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BrazosApp.Models.Users", b =>
                {
                    b.HasOne("BrazosApp.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BrazosApp.Models.Territory", b =>
                {
                    b.Navigation("Inspectors");
                });

            modelBuilder.Entity("BrazosApp.Models.Users", b =>
                {
                    b.Navigation("TerritoryWiseInspectors")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
